// <auto-generated />
using System;
using CRUDGen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDGen.Migrations
{
    [DbContext(typeof(DbCtx))]
    [Migration("20230120160715_Added_I")]
    partial class Added_I
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CRUDGen.Models.ARQ_EXPEDIENT", b =>
                {
                    b.Property<int>("ARQ_EXPEDIENT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ARQ_EXPEDIENT_ID"), 1L, 1);

                    b.Property<string>("ALFRESCOPATH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARQ_APPFASES_NI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARQ_APP_NI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ARQ_EVENT_FK")
                        .HasColumnType("int");

                    b.Property<string>("ARQ_EXPEDIENTESTAT_NI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARQ_EXPEDIENTTIPUS_NI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARQ_USUARI_NI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUDIT_APP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AUDIT_DATAOPERACIOBBDD")
                        .HasColumnType("datetime2");

                    b.Property<string>("AUDIT_OPERACIOBBDD_NI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUDIT_USER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONCURRENCYGUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESBORRAT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOMINTERN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOMVISIBLE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ARQ_EXPEDIENT_ID");

                    b.ToTable("ARQ_EXPEDIENT");
                });

            modelBuilder.Entity("CRUDGen.Models.ARQ_EXPEDIENT_I", b =>
                {
                    b.Property<int>("ARQ_EXPEDIENT_I_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ARQ_EXPEDIENT_I_ID"), 1L, 1);

                    b.Property<int>("ARQ_EXPEDIENT_ID")
                        .HasColumnType("int");

                    b.Property<string>("AUDIT_APP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AUDIT_DATAOPERACIOBBDD")
                        .HasColumnType("datetime2");

                    b.Property<string>("AUDIT_OPERACIOBBDD_NI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUDIT_USER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESBORRAT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOMINTERN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOMVISIBLE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ARQ_EXPEDIENT_I_ID");

                    b.HasIndex("ARQ_EXPEDIENT_ID");

                    b.ToTable("ARQ_EXPEDIENT_I");
                });

            modelBuilder.Entity("CRUDGen.Models.ARQ_EXPEDIENT_I", b =>
                {
                    b.HasOne("CRUDGen.Models.ARQ_EXPEDIENT", "ARQ_EXPEDIENT")
                        .WithMany()
                        .HasForeignKey("ARQ_EXPEDIENT_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ARQ_EXPEDIENT");
                });
#pragma warning restore 612, 618
        }
    }
}
