// <auto-generated />
using System;
using CRUDGen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDGen.Migrations
{
    [DbContext(typeof(DbCtx))]
    [Migration("20230130231915_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CRUDGen.Models.ARQDemo_Inetum", b =>
                {
                    b.Property<int>("ARQ_Id")
                        .HasColumnType("int");

                    b.HasKey("ARQ_Id");

                    b.ToTable("ARQDemo_Inetum");
                });

            modelBuilder.Entity("CRUDGen.Models.ARQDemo_Inetum_Idioma", b =>
                {
                    b.Property<int>("ARQDemo_Inetum_Idioma_Id")
                        .HasColumnType("int");

                    b.Property<int?>("ARQDemo_InetumARQ_Id")
                        .HasColumnType("int");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ARQDemo_Inetum_Idioma_Id");

                    b.HasIndex("ARQDemo_InetumARQ_Id");

                    b.ToTable("ARQDemo_Inetum_Idioma");
                });

            modelBuilder.Entity("CRUDGen.Models.ARQDemo_Inetum_Idioma", b =>
                {
                    b.HasOne("CRUDGen.Models.ARQDemo_Inetum", null)
                        .WithMany("ARQDemo_Inetum_Idioma")
                        .HasForeignKey("ARQDemo_InetumARQ_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CRUDGen.Models.ARQDemo_Inetum", b =>
                {
                    b.Navigation("ARQDemo_Inetum_Idioma");
                });
#pragma warning restore 612, 618
        }
    }
}
